apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: poll
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
        - path: /poll.dop.io
          backend:
            serviceName: poll
            servicePort: 80