apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll
  labels:
    name: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      name: poll
  template:
    metadata:
      labels:
        name: poll
    spec:
      containers:
      - env:
        - name: REDIS_HOSTNAME
          value: redis
        - name: REDIS_PORT
          value: "80"
        image: epitechcontent/t-dop-600-poll:k8s
        name: poll
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
status: {}
