apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: poll
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: REDIS_HOSTNAME
          value: redis
        - name: REDIS_PORT
          value: "80"
        image: poll
        name: poll
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
