apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: poll
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: poll
            servicePort: 80