apiVersion: v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: 5432
        image: postgres:12
        name: postgres
        ports:
        - port: 5432
        resources: {}
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/schema.sql
          name: postgres-schema
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      restartPolicy: Always
      volumes:
      - name: postgres-schema
        persistentVolumeClaim:
          claimName: postgres-schema
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
status: {}
