apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - image: redis:5.0
        name: redis
        ports:
        - containerPort: 6379
      restartPolicy: Always
status: {}
