apiVersion: v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  strategy: {}
  template:
    spec:
      containers:
      - image: redis:5.0
        name: redis
        resources: {}
      restartPolicy: Always
  ports:
  - name: "6379"
    port: 6379
status: {}
