apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: result
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
        - path: /result.dop.io
          backend:
            serviceName: result
            servicePort: 80