apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result
  template:
    metadata:
      labels:
        name: result
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_DNS
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: postgres
        image: epitechcontent/t-dop-600-result:k8s
        name: result
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
status: {}
