apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    name: result
spec:
  replicas: 2
  selector:
    matchLabels:
      name: result
  template:
    metadata:
      labels:
        name: result
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret
        image: epitechcontent/t-dop-600-result:k8s
        name: result
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 128Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - poll
            topologyKey: kubernetes.io/hostname
      restartPolicy: Always
status: {}
