kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: kube-public
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30021
      name: web
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30042
      name: admin
  type: NodePort
