apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker
  template:
    metadata:
      labels:
        name: worker
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: postgres-config
        - configMapRef:
            name: redis
        - secretRef:
            name: postgres-secret
        image: epitechcontent/t-dop-600-worker:k8s
        name: worker
        resources:
          limits:
            memory: 256Mi
      restartPolicy: Always
status: {}
