apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker
  template:
    metadata:
      labels:
        name: worker
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_DNS
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: postgres
        - name: REDIS_HOSTNAME
          value: redis
        - name: REDIS_PORT
          value: "80"
        image: epitechcontent/t-dop-600-worker:k8s
        name: worker
      restartPolicy: Always
status: {}
